package org.escidoc.browser.ui.maincontent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class SearchResults extends VerticalLayout {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tblResults;
	private final int appHeight;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchResults(final int appHeight) {
		this.appHeight = appHeight;
        setMargin(true);
        this.setHeight("100%");
        final CssLayout cssLayout = new CssLayout();
        cssLayout.setWidth("100%");
        cssLayout.setHeight("100%");
        
		final BreadCMenu bm = new BreadCMenu(cssLayout,"search");
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tblResults
		tblResults = new Table();
		tblResults.setWidth("100.0%");
		tblResults.setHeight("100.0%");
		tblResults.setImmediate(false);
		cssLayout.addComponent(tblResults);
		
		addComponent(cssLayout);
	}

}
