package org.escidoc.browser.ui.maincontent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextField;
/**
 * NOT READY YET
 * @author ARB
 *
 */
public class SearchSimple extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TextField textField_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchSimple() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setWidth("168px");
		textField_1.setHeight("-1px");
		textField_1.setImmediate(false);
		mainLayout.addComponent(textField_1, "top:48.0%;left:398.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		button_1.setCaption("Button");
		button_1.setImmediate(true);
		mainLayout.addComponent(button_1, "top:48.0%;left:581.0px;");
		
		return mainLayout;
	}

}
