package org.escidoc.browser.ui.maincontent;

import org.escidoc.browser.ui.MainSite;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.BaseTheme;

public class SearchResults extends VerticalLayout {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tblResults;
	private final int appHeight;
	private final Button btnAdvancedSearch;
	private MainSite mainSite;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param mainSite 
	 */
	public SearchResults(MainSite mainSite, final int appHeight) {
		this.mainSite = mainSite;
		this.appHeight = appHeight;
		setWidth("100.0%");
		setHeight(appHeight+"px");
		setMargin(true);
        final CssLayout cssLayout = new CssLayout();
        cssLayout.setWidth("100%");
        cssLayout.setHeight("100%");

        //Here comes the breadcrumb menu
		final BreadCrumbMenu bm = new BreadCrumbMenu(cssLayout,"search");

		//here comes the Advanced search label
		// Login
		this.btnAdvancedSearch = new Button("Advanced Search", this, "onClick");
		this.btnAdvancedSearch.setStyleName(BaseTheme.BUTTON_LINK);
		this.btnAdvancedSearch.setImmediate(true);
		this.btnAdvancedSearch.setStyleName("v-button-link floatright");
		cssLayout.addComponent(this.btnAdvancedSearch);
		
		// tblResults
		tblResults = new Table();
		tblResults.setWidth("100.0%");
		tblResults.setHeight("100.0%");
		tblResults.setImmediate(false);
		cssLayout.addComponent(tblResults);
		
		addComponent(cssLayout);
	}

	/**
     * Handle the Login Event!
     * At the moment a new window is opened to escidev6 for login
     * TODO consider including the window of login from the remote server in a 
     * iframe within the MainContent Window
     * @param event
     */
	public void onClick(Button.ClickEvent event) {
		SearchAdvanced srch = new SearchAdvanced(mainSite, appHeight);
		this.mainSite.openTab(srch , "Advanced Search");
	}
}
