package org.escidoc.browser.ui.mainpage;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class LoginForm extends VerticalLayout {

    @AutoGenerated
    private final Button Login;

    @AutoGenerated
    private TextField password;

    @AutoGenerated
    private TextField username;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public LoginForm() {
        final CssLayout cssLayout = new CssLayout();
        cssLayout.setWidth("500px");
        // Login
        Login = new Button();
        // Login.setWidth("60px");
        // Login.setHeight("15px");
        Login.setCaption("Login");
        Login.setImmediate(true);
        // cssLayout.addComponent(Login, "top:2.0px;left:385.0px;");
        cssLayout.addComponent(Login);
        addComponent(cssLayout);
    }

}
